#!/bin/sh /etc/rc.common
# openuf init script (procd)

USE_PROCD=1
START=95
STOP=10

CONF=/etc/openuf/openuf.conf
PROG=/usr/sbin/openuf

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" -c "$CONF"
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    killall openuf 2>/dev/null
}

reload_service() {
    stop_service
    start_service
}
